events {}

http {
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        autoindex off;

        location /releases/ {
            limit_except GET {
                deny all;
            }
            try_files $uri =404;
            default_type application/octet-stream;
        }

        location / {
            return 404;
        }
    }
}
